# FAKEBOOK_LOGIN_URL = 'http://fring.ccs.neu.edu/accounts/login/?next=/fakebook/'
# FAKEBOOK_DOMAIN_URL = 'http://fring.ccs.neu.edu'
FAKEBOOK_LOGIN_URL = 'http://cs5700sp15.ccs.neu.edu/accounts/login/?next=/fakebook/'
FAKEBOOK_DOMAIN_URL = 'http://cs5700sp15.ccs.neu.edu'
NEXT_VAL = '/fakebook/'
VALUES_USERNAME = 'username'
VALUES_PASSWORD = 'password'
VALUES_NEXT = 'next'
VALUES_CSRF = 'csrfmiddlewaretoken'
NUM_THREADS = 100
